apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t34lwo8f1-nodejs 
  janus-idp.io/tekton: t34lwo8f1-nodejs
  backstage.io/kubernetes-id: t34lwo8f1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t34lwo8f1-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  